package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     *
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */

    /* my code for Join */
    private JoinPredicate p;
    private DbIterator child1;
    private DbIterator child2;
    /* my code for Join */

    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
        /* my code for Join */
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        /* my code for Join */
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        //return null;
        /* my code for Join */
        return p;
        /* my code for Join */
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        //return null;
        /* my code for Join */
        return child1.getTupleDesc().getFieldName(p.getField1());
        /* my code for Join */
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        //return null;
        /* my code for Join */
        return child2.getTupleDesc().getFieldName(p.getField2());
        /* my code for Join */
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        //return null;
        /* my code for Join */
        TupleDesc td1 = child1.getTupleDesc();
        TupleDesc td2 = child2.getTupleDesc();
        return TupleDesc.merge(td1, td2);
        /* my code for Join */
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        /* my code for Join */
        child1.open();
        child2.open();
        super.open();
        /* my code for Join */
    }

    public void close() {
        // some code goes here
        /* my code for Join */
        child1.close();
        child2.close();
        super.close();
        /* my code for Join */
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        /* my code for Join */
        child1.rewind();
        child2.rewind();
        /* my code for Join */
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        //return null;
        /* my code for Join */
        while (child1.hasNext()) {
            Tuple tuple1 = child1.next();
            while (child2.hasNext()) {
                Tuple tuple2 = child2.next();
                if (p.filter(tuple1, tuple2)) {
                    Tuple tuple = new Tuple(TupleDesc.merge(tuple1.getTupleDesc(), tuple2.getTupleDesc()));
                    Iterator<Field> field1 = tuple1.fields();
                    Iterator<Field> field2 = tuple2.fields();
                    int index = 0;
                    while (field1.hasNext()) {
                        tuple.setField(index, field1.next());
                        index++;
                    }
                    while (field2.hasNext()) {
                        tuple.setField(index, field2.next());
                        index++;
                    }
                    return tuple;
                }
            }
            child2.rewind();
        }
        return null;
        /* my code for Join */

    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        //return null;
        /* my code for Join */
        return new DbIterator[] {child1, child2};
        /* my code for Join */
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
        /* my code for Join */
        children[0] = child1;
        children[1] = child2;
        /* my code for Join */
    }

}
